import type { Metadata } from "next";
import { Toaster } from 'sonner'
import "../globals.css";
import { Header } from "@/components/header";
import { ArrowLeft } from "@phosphor-icons/react/dist/ssr";
import { ThemeProvider } from "next-themes";
import localFont from 'next/font/local'
import Image from "next/image";
import Link from "next/link";


const westwood = localFont({
    src: "./westwood.woff2",
    display: "swap"
})

export const metadata: Metadata = {
    title: "SPFC | Easter Egg",
    description: "Generated by create next app",
};

export default function SPFCLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
        >
            <body className={`${westwood.className} antialiased`}>
                <main className="relative flex min-h-screen w-full items-center justify-center bg-white text-black">
                    <Link href={'/'} className="absolute top-10 left-10 flex items-center justify-center rounded-full bg-black p-2 shadow-inner shadow-white/65 " type="button">
                        <ArrowLeft color="white" />
                    </Link>
                    {children}
                </main>
            </body>
        </html>
    );
}